import Head from 'next/head'
import Navbar from '../components/navbar'
import Subnavbar from '../components/subnavbar'
import Aboutme from '../components/aboutme'
import Proyects from '../components/proyects'



export default function Home() {
  return (
    <>
      <Head>
        <title>NomaDiix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/nomadiix.ico" />
      </Head>

      <div className='gradient-03 z-0'/>
      <Navbar/>
      <Subnavbar/>
      <div className='relative'>
      <div className=' gradient-03 z-0 '/>
        <Aboutme/>
      </div>

      <div className='relative'>
        <div className='gradient-04 z-0'/>
        <Proyects/>
      </div>

      
    </>
  )
}
